### ISSUE TITLE
파이썬 버전 이슈

### ISSUE THREAD

**Issue by 5pponent** [project-sulsul/sulsul-backend#12]
현재 서버에서 파이썬 3.12 버전 사용중인데, 이번에 딥러닝 요구 모듈 설치하면서 이슈가 발생했습니다

torch 1.13.0 버전 모듈이 파이썬 3.11 버전 미만에서만 사용 가능해서 현재 서버에 배포가 불가능합니다

**Comment by mopil** [comment]
디비 버전 이슈도 있었는데 이 참에 버전 내려버리시죠

**Comment by 5pponent** [comment]
> 디비 버전 이슈도 있었는데 이 참에 버전 내려버리시죠

이거는 어떤 이슈인가요?

**Comment by mopil** [comment]
아 디비버전 이슈가 아니라 람다 버전 이슈였네요
